version: '3'
services:
  presto:
    hostname: presto
    image: 'prestodb/presto:0.290-edge18'
    container_name: presto
    ports:
      - '8080:8080'
    volumes:
      - './presto/presto-cli-0.289-executable.jar:/usr/bin/presto'
      - './presto/minio.properties:/opt/presto-server/etc/catalog/minio.properties'
  hadoop:
    hostname: hadoop-master
    image: 'prestodb/hive3.1-hive:5'
    container_name: hadoop-master
    environment:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
    volumes:
      - './hadoop/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml'
      - './hadoop/ibm-cos-java-sdk-core-2.13.6.jar:/opt/hive/lib/ibm-cos-java-sdk-core-2.13.6.jar'
      - './hadoop/sdk-core-9.22.0.jar:/opt/hive/lib/sdk-core-9.22.0.jar'
      - './hadoop/hadoop-aws-3.4.1.jar:/opt/hive/lib/hadoop-aws-3.4.1.jar'
      - './hadoop/aws-java-sdk-1.12.777.jar:/opt/hive/lib/aws-java-sdk-1.12.777.jar'
  mc-job:
    image: 'minio/mc:latest'
    environment:
      MC_HOST_presto: "https://minio:minio123@play.min.io"
    volumes:
      - './minio/data:/minio'
    entrypoint: |
      /bin/bash -c "
      /usr/bin/mc mb --quiet presto/customer-data-text;
      /usr/bin/mc mb --quiet presto/customer-data-orc;
      /usr/bin/mc mirror minio/customer-data-text presto/customer-data-text;
      "
